version: '3.8'

services:
  teslo-shop:
    image: postgres:15.3
    container_name: teslo-shop
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=teslo-shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./postgres:/var/lib/postgresql/data